### ISSUE TITLE
Klinische Aspekte missing report from 2021-07-21

### ISSUE THREAD

**Issue by corneliusroemer** [zidatalab/covid19dashboard#65]
Thanks for archiving the `Klinische Aspekte` xls from the RKI website (they don't seem to archive it) :/

Unfortunately, it looks like you missed off one week of reports: 2021-07-21

Do you intend to keep archiving? What's the reason for the folder being named "old"?

Apparently some people have archives going back longer until December. Would it be worth adding them in a PR?

This archive could be quite valuable for Fore/Nowcasting expected hospital admissions.
https://github.com/zidatalab/covid19dashboard/tree/master/data/klinische_aspekte_old

![image](https://user-images.githubusercontent.com/25161793/127888142-aec7d5f9-3244-4503-9f6d-c875b666a346.png)

**Comment by edg-stg** [comment]
This folder is so far just a by-product of a report generated by a manually started script once a week.
We missed the file for the week of the 19 to 25 July, unfortunately (when RKI changed the updates of all COVID excel tables to Thursday).
The sheets with data per KW of the excel contain the whole historic information since Meldewoche/KW 10 in 2020. The numbers get updated every week for past weeks, though (because of Nachmeldungen). But I don't see if these changes are of bigger importance to someone - or are they for you?

**Comment by corneliusroemer** [comment]
I see, well it's a very useful by-product, because it allows for construction of a Now-/Forecast.

I'll just fork, add more files from the past and open a PR. It's good to have this kind of stuff on the record.

As far as I know, you're the only one to archive this sheet on Github. Others are archiving the case/death data every day, but no one apart from you has published an archive of Klinische Daten so thanks for that even if unintended ;)
